# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception

# Walks commits in the LLVM submodule creating new commits for each update.
# New commits are created on the auto-integrate branch starting from the LLVM
# commit at the main branch (exclusive). Each commit has new LLVM build files
# generated and is tagged with the appropriate LLVM commit.

name: Auto Integrate

on:
  push:
    branches: [main]
  workflow_dispatch:
  schedule:
    # Every 15 minutes
    - cron: "*/15 * * * *"

jobs:
  auto_integrate:
    # Don't run on forks
    if: github.repository == 'google/llvm-bazel'
    runs-on: ubuntu-18.04
    env:
      MERGING_BRANCH: "main"
      INTEGRATION_BRANCH: "auto-integrate"
    steps:
      # Busy-wait for previous workflow invocations to finish. GitHub actions do
      # not provide a good way to limit the number of instances of a single
      # workflow. We don't want multiple of these running at once since they
      # push and will invalidate eachother.
      - name: Turnstyle
        uses: softprops/turnstyle@v1
        with:
          same-branch-only: false
          abort-after-seconds: 900
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Checking out repository
        uses: actions/checkout@v2
        with:
          # Get all history. Unfortunately necessary for what we need to do.
          fetch-depth: 0
          submodules: true
          ref: ${{ env.MERGING_BRANCH }}
          token: ${{ secrets.WRITE_ACCESS_TOKEN }}
      - name: Fetching integration branch
        run: |
          git fetch --no-tags --prune origin "${INTEGRATION_BRANCH?}:${INTEGRATION_BRANCH?}"
      - name: Setting git config
        run: |
          git config --local user.email "llvm-bazel-github-bot@google.com"
          git config --local user.name "Auto Integrate Action"
      - name: Tagging new commits on main
        if: ${{ github.event_name == 'push' }}
        run: ./scripts/tag_since.sh "${{ github.event.before }}"
      - name: Merging in changes
        run: |
          if ! git merge-base --is-ancestor "${MERGING_BRANCH?}" "${INTEGRATION_BRANCH?}"; then
            ./scripts/clobber_merge.sh "${INTEGRATION_BRANCH?}" "${MERGING_BRANCH?}"
          else
            echo "${INTEGRATION_BRANCH?} already branches from ${MERGING_BRANCH?}"
          fi
          git checkout "${INTEGRATION_BRANCH?}"
          git submodule update
      - name: Running auto integration
        run: ./scripts/auto_integrate.sh
      - name: Pushing changes
        run: |
          git push origin "${INTEGRATION_BRANCH?}"
          git push origin --force --tags
